version: 2

sources:
  - name: stg     
    schema: PUBLIC       
    database: DBTDEMO
    tables:
      - name: CUSTOMER_PRODUCT
        description: Raw customer_product daa extracted from source 

        columns:
          - name: customer_id
            description: "Unique identifier for customers."
            data_tests:
              - not_null

          - name: product_id
            description: "Unique identifier for products."
            data_tests:
              - not_null
          - name: customer_status
            data_tests:
              - accepted_values:
                  arguments:
                    values: ["ACTIVE", "INACTIVE"]
                  config: 
                    severity: warn