version: 2

sources:
  - name: stg          # this is the label you'll reference in source('public', ...)
    schema: PUBLIC          # the ACTUAL Snowflake schema name (only needed if it differs from `name`)
    database: DBTDEMO       # optional — defaults to your target database if omitted
    tables:
      - name: CUSTOMER_PRODUCT
        description: Raw customer_product daa extracted from source 

        columns:
          - name: customer_id
            description: "Unique identifier for customers."
            data_tests:
              - not_null

          - name: product_id
            description: "Unique identifier for products."
            data_tests:
              - not_null